name: EntityControl
main: net.yeticraft.xxtraineexx.entitycontrol.EntityControl
version: 1.2
authors: [XxTRAINEExX]

commands:
  ec:
    description: Interact with Entity Control
    usage: /<command>
  entitycontrol:
    description: Interact with Entity Control
    usage: /<command>
permissions:
    ec.*:
        description: Gives access to all EntityControl features
        children:
            ec.command: true
            ec.go: true
            ec.debug: true
            ec.reload: true
            ec.toggle: true
    ec.command:
        description: Allows player access to MSC commands
        default: op
    ec.go:
        description: Allows players access to GO command
        default: op
    ec.debug:
        description: Enables EC debugging
        default: op
    ec.reload:
        description: Reloads config from disk
        default: op
    ec.toggle:
        description: Turns the plugin ON and OFF
        default: op